/**
 * 「常用设置」页展示的设置清单（docs/v28-schedule.md 三稿）。
 *
 * 沿革：一稿把 519 项全量铺进「全部设置」页；二稿收敛为 108 项精选（与常用设置 42 项零交集）；
 * 三稿按用户口径删去 33 项（外观零碎 / 供应商整组 / Shell 与脚本的补充项 / 工具整组 /
 * worktree 目录 / 外部命令来源），并把两个页签**合并成一页**——本清单 = 原常用 42 项 +
 * 精选剩余 75 项 = **117 项**；「常用设置」页是 omp 设置在本应用的唯一面，
 * 全量清单在终端 `omp config list` 看。
 *
 * 维护契约（`settingsList.test.ts` 守着）：
 * - 基础池 = omp TUI `/settings` 面板可见项（二进制里带 `ui` 元数据的那批，18.4.4 = 387 项）；
 * - 无重复；每一项在名称表（`ompSettingNames.ts`）里都有条目（行标题有中英短名）；
 *   规模 100–140（防被扩回全量）；三稿删掉的 33 项不得回流（测试钉住）；
 * - 顺序照上游人读清单（面板按上游分组渲染，组内顺序 = `omp config list` 的顺序）；
 * - 上游升级后新增的键**不会自动进来**——判断新键值不值得进本页时，先看它在不在
 *   TUI `/settings` 面板里。
 */
import type { Text } from "./locale";

export const SETTINGS_LIST: readonly string[] = [
 // —— appearance
 "theme.dark",
 "theme.light",
 "symbolPreset",
 "composer.shape",
 "composer.tokenRate",
 "statusLine.preset",
 "statusLine.contextLine",
 "statusLine.compactThinkingLevel",
 "terminal.showImages",
 "images.autoResize",
 "images.blockImages",
 "tui.renderMermaid",
 "tui.reactions",
 "tui.titleState",
 "tui.titleSpinner",
 "tui.mouse",
 "tui.tight",
 "display.smoothStreaming",
 "display.hideToolActivity",
 "display.showTokenUsage",
 "display.showTurnTime",
 "showHardwareCursor",
 "task.showResolvedModelBadge",

 // —— context
 "contextPromotion.enabled",
 "extendedContext",
 "compaction.enabled",
 "compaction.midTurnEnabled",
 "compaction.thresholdPercent",
 "compaction.thresholdTokens",
 "compaction.idleEnabled",

 // —— files
 "edit.mode",
 "edit.fuzzyMatch",
 "edit.streamingAbort",
 "edit.blockAutoGenerated",
 "edit.enforceSeenLines",
 "readLineNumbers",
 "read.defaultLimit",
 "read.renderMarkdown",
 "read.summarize.enabled",
 "read.toolResultPreview",
 "lsp.enabled",
 "lsp.lazy",
 "lsp.shared",
 "lsp.formatOnWrite",
 "lsp.diagnosticsOnWrite",
 "lsp.diagnosticsOnEdit",

 // —— interaction
 "autoResume",
 "git.enabled",
 "steeringMode",
 "followUpMode",
 "interruptMode",
 "tui.vimMode",
 "doubleEscapeAction",
 "spelling.typoDetection",
 "spelling.autocomplete",
 "spelling.autocorrect",
 "startup.checkUpdate",
 "update.channel",
 "marketplace.autoUpdate",
 "startup.changelogMode",
 "magicKeywords.enabled",
 "completion.notify",
 "error.notify",
 "ask.timeout",
 "ask.notify",
 "recap.enabled",
 "power.sleepPrevention",
 "features.unexpectedStopDetection",
 "tools.approvalMode",
 "stt.enabled",

 // —— internal
 "compaction.autoContinue",
 "skills.enabled",

 // —— memory
 "memory.backend",
 "autolearn.enabled",
 "mnemopi.scoping",
 "mnemopi.autoRecall",
 "mnemopi.autoRetain",
 "hindsight.scoping",
 "hindsight.autoRecall",
 "hindsight.autoRetain",

 // —— model
 "images.describeForTextModels",
 "defaultThinkingLevel",
 "hideThinkingBlock",
 "includeWorkspaceTree",
 "personality",
 "temperature",
 "textVerbosity",
 "retry.maxRetries",
 "retry.waitForUsageReset",
 "retry.usageAwareFallback",
 "retry.usageReservePolicy",
 "providers.autoThinkingMaxEffort",

 // —— shell
 "bash.enabled",
 "bash.allowCompoundCommands",
 "bashInterceptor.enabled",
 "eval.py",
 "eval.js",

 // —— tasks
 "task.isolation.enabled",
 "task.isolation.apply",
 "task.isolation.merge",
 "task.isolation.commits",
 "task.eager",
 "task.enableEffort",
 "task.maxConcurrency",
 "task.enableLsp",
 "task.maxRecursionDepth",
 "plan.enabled",
 "plan.defaultOnStartup",
 "goal.enabled",

 // —— tools
 "todo.enabled",
 "computer.enabled",
 "checkpoint.enabled",
 "fetch.enabled",
 "github.enabled",
 "web_search.enabled",
 "dev.autoqa",
 "browser.enabled",
];

/** 上面数组的集合形式（面板渲染时每项 O(1) 命中）。 */
export const SETTINGS_LIST_SET: ReadonlySet<string> = new Set(SETTINGS_LIST);

/**
 * 分组归位：上游把这两个行为开关归在 `internal`（那组其余全是凭证与机器状态，不适合放
 * 行为开关）；按原「常用设置」页的归类显示（压缩后自动继续 → 会话与上下文；技能发现 → 任务与技能）。
 */
export const SETTING_SECTION_OVERRIDES: Record<string, string> = {
 "compaction.autoContinue": "context",
 "skills.enabled": "tasks",
};

/**
 * 行内标注（键名下第二行的附加信息）：
 * - `tuiOnly`：只影响 omp 自己的终端 TUI（plan / goal 是功能总闸，实测 RPC / 壳侧无可观测差异）；
 * - `minusOneIsDefault`：数字的 `-1` 表示「用 omp 默认」（当前值为 -1 时行内提示）。
 */
export const SETTING_NOTES: Record<string, { tuiOnly?: true; minusOneIsDefault?: true }> = {
 "plan.enabled": { tuiOnly: true },
 "goal.enabled": { tuiOnly: true },
 "compaction.thresholdPercent": { minusOneIsDefault: true },
 temperature: { minusOneIsDefault: true },
};

/**
 * `composer.shape` 的内置形态表（omp 源里的静态八项；插件还能注册更多——壳侧只含内置，
 * 当前值不在表里时界面原样补一条）。
 */
export const COMPOSER_SHAPES = ["band", "box", "claude", "pi", "borderless", "rule", "field", "rail"] as const;

/**
 * 「string 但取值有限」的键（上游 `ui: { options: "runtime" }`；omp 18.4.4 恰好 3 个）
 * 的下拉取值：
 * - `theme.dark` / `theme.light`：运行时主题列表（后端 `list_omp_themes` = 内置 102 个 ∪
 *   `<agentDir>/themes/*.json`，与 omp TUI 的 `availableThemes` 同口径）；
 * - `composer.shape`：内置八形态（`COMPOSER_SHAPES`）；
 * - 其它键（含普通 string 键——路径 / URL 这类自由输入）返回 `null` = 用文本输入框。
 */
export function runtimeChoiceValues(key: string, themeNames: readonly string[]): readonly string[] | null {
 if (key === "theme.dark" || key === "theme.light") return themeNames;
 if (key === "composer.shape") return COMPOSER_SHAPES;
 return null;
}

/**
 * 下拉选项的翻译（键 →（上游取值 → 字典键 `sv*`））。
 * 与上游同一套「选项表 + `sv*` 字典」做法：
 * - **普通词**翻成界面语言（on / off / auto、模式与档位名…）；多个键重复出现的取值共享
 *   一个字典键（`svOn` / `svOff` / `svAuto` / `svDefault` / `svNone`）；
 * - **专有名词与档位名原样显示上游取值**（`speech.voice` 的音色名、引擎名、`xhigh` / `max`、
 *   `theme.dark` / `theme.light` 的 100+ 主题名——硬翻反而误导）：**没配 label 的键 / 取值
 *   原样显示上游值**；
 * - `composer.shape`（string 但取值有限）的八个形态也在这里配翻译；
 * - `settingsList.test.ts` 守着：表里的键必须在清单里、每个字典键中英非空、
 *   字典里的每个 `sv*` 键都被本表引用（不许有孤儿——删键时同步清翻译）。
 */
export const OPTION_LABELS: Record<string, Record<string, keyof Text>> = {
 "symbolPreset": {
  unicode: "svSymbolsUnicode",
  nerd: "svSymbolsNerd",
  ascii: "svSymbolsAscii",
 },
 "composer.shape": {
  band: "svShapeBand",
  box: "svShapeBox",
  claude: "svShapeClaude",
  pi: "svShapePi",
  borderless: "svShapeBorderless",
  rule: "svShapeRule",
  field: "svShapeField",
  rail: "svShapeRail",
 },
 "statusLine.preset": {
  default: "svDefault",
  minimal: "svPresetMinimal",
  compact: "svPresetCompact",
  full: "svPresetFull",
  nerd: "svPresetNerd",
  ascii: "svPresetAscii",
  custom: "svPresetCustom",
 },
 "statusLine.contextLine": {
  off: "svOff",
  percentage: "svCtxLinePercentage",
  annotated: "svCtxLineAnnotated",
  embedded: "svCtxLineEmbedded",
 },
 "tui.titleSpinner": {
  braille: "svSpinnerBraille",
  pulse: "svSpinnerPulse",
  dots: "svSpinnerDots",
  line: "svSpinnerLine",
 },
 interruptMode: {
  immediate: "svInterruptImmediate",
  wait: "svInterruptWait",
 },
 doubleEscapeAction: {
  rewind: "svEscRewind",
  tree: "svEscTree",
  none: "svNone",
 },
 "spelling.autocomplete": {
  off: "svOff",
  auto: "svAuto",
 },
 "update.channel": {
  stable: "svChannelStable",
  canary: "svChannelCanary",
 },
 "marketplace.autoUpdate": {
  off: "svOff",
  notify: "svMarketNotify",
  auto: "svAuto",
 },
 "startup.changelogMode": {
  summary: "svChangelogSummary",
  expanded: "svChangelogExpanded",
  hidden: "svChangelogHidden",
 },
 "completion.notify": { on: "svOn", off: "svOff" },
 "error.notify": { on: "svOn", off: "svOff" },
 "ask.notify": { on: "svOn", off: "svOff" },
 "features.unexpectedStopDetection": {
  none: "svOff",
  mechanical: "svStopMechanical",
  smart: "svStopSmart",
 },
 "mnemopi.scoping": {
  global: "svScopeGlobal",
  "per-project": "svScopeProject",
  "per-project-tagged": "svScopeProjectTagged",
 },
 "hindsight.scoping": {
  global: "svScopeGlobal",
  "per-project": "svScopeProject",
  "per-project-tagged": "svScopeProjectTagged",
 },
 personality: {
  default: "svDefault",
  friendly: "svPersonalityFriendly",
  pragmatic: "svPersonalityPragmatic",
  none: "svNone",
 },
 textVerbosity: { low: "svVerbosityLow", medium: "svVerbosityMedium", high: "svVerbosityHigh" },
 "retry.usageReservePolicy": {
  confirm: "svReserveConfirm",
  auto: "svAuto",
  "fail-closed": "svReserveFailClosed",
 },
 "tools.approvalMode": {
  "always-ask": "svApprovalAsk",
  write: "svApprovalWrite",
  yolo: "svApprovalYolo",
 },
 "memory.backend": {
  off: "svMemOff",
  local: "svMemLocal",
  hindsight: "svMemHindsight",
  mnemopi: "svMemMnemopi",
  sharpshooter: "svMemSharpshooter",
 },
 "task.isolation.merge": {
  patch: "svMergePatch",
  branch: "svMergeBranch",
 },
 "power.sleepPrevention": {
  off: "svSleepOff",
  idle: "svSleepIdle",
  display: "svSleepDisplay",
  system: "svSleepSystem",
 },
 steeringMode: {
  all: "svQueueAll",
  "one-at-a-time": "svQueueOne",
 },
 followUpMode: {
  all: "svQueueAll",
  "one-at-a-time": "svQueueOne",
 },
 "task.isolation.commits": { generic: "svCommitsGeneric", ai: "svCommitsAi" },
 "task.eager": { default: "svDefault", preferred: "svEagerPreferred", always: "svEagerAlways" },
};
