/** Tauri command / event 通道常量，前后端共用命名。 */
export const IPC = {
  // commands
  locateOmp: "locate_omp",
  getHealth: "get_health",
  getModels: "get_models",
  refreshModels: "refresh_models",
  getOverlay: "get_overlay",
  listProjects: "list_projects",
  addProject: "add_project",
  removeProject: "remove_project",
  relocateProject: "relocate_project",
  listSessions: "list_sessions",
  listArchivedSessions: "list_archived_sessions",
  searchSessions: "search_sessions",
  createSession: "create_session",
  openSession: "open_session",
  archiveSession: "archive_session",
  unarchiveSession: "unarchive_session",
  deleteSession: "delete_session",
  archiveSessions: "archive_sessions",
  unarchiveSessions: "unarchive_sessions",
  deleteSessions: "delete_sessions",
  renameSessionNote: "rename_session_note",
  getHistory: "get_history",
  sendMessage: "send_message",
  steerMessage: "steer_message",
  followUpMessage: "follow_up_message",
  compactSession: "compact_session",
  branchSession: "branch_session",
  runSlash: "run_slash",
  readImageFile: "read_image_file",
  checkPaths: "check_paths",
  completePath: "complete_path",
  stopSession: "stop_session",
  approve: "approve",
  respondUi: "respond_ui",
  setModel: "set_model",
  setThinking: "set_thinking",
  getSessionRuntime: "get_session_runtime",
  getGitInfo: "get_git_info",
  getGlobalApproval: "get_global_approval",
  setGlobalApproval: "set_global_approval",
  setSessionApproval: "set_session_approval",
  setOmpPath: "set_omp_path",
  // 供应商（设置 › 供应商）：login / logout / modelRoles
  listProviders: "list_providers",
  getProviderLogin: "get_provider_login",
  startProviderLogin: "start_provider_login",
  providerLoginInput: "provider_login_input",
  cancelProviderLogin: "cancel_provider_login",
  logoutProvider: "logout_provider",
  getModelRoles: "get_model_roles",
  setModelRole: "set_model_role",
  // events
  sessionEvent: (id: string) => `omp-event://${id}`,
  sessionStatus: (id: string) => `omp-status://${id}`,
  sessionRuntime: (id: string) => `omp-state://${id}`,
  health: "omp-status://health",
  /** 供应商登录进度（payload = 全量 ProviderLoginStatus 快照）。 */
  providerLogin: "omp-provider://login",
} as const;
