/** Tauri command / event 通道常量，前后端共用命名。 */
export const IPC = {
  // commands
  locateOmp: "locate_omp",
  getHealth: "get_health",
  getModels: "get_models",
  refreshModels: "refresh_models",
  getOverlay: "get_overlay",
  listProjects: "list_projects",
  addProject: "add_project",
  removeProject: "remove_project",
  relocateProject: "relocate_project",
  listSessions: "list_sessions",
  searchSessions: "search_sessions",
  createSession: "create_session",
  openSession: "open_session",
  archiveSession: "archive_session",
  unarchiveSession: "unarchive_session",
  deleteSession: "delete_session",
  archiveSessions: "archive_sessions",
  deleteSessions: "delete_sessions",
  renameSessionNote: "rename_session_note",
  getHistory: "get_history",
  sendMessage: "send_message",
  readImageFile: "read_image_file",
  checkPaths: "check_paths",
  stopSession: "stop_session",
  approve: "approve",
  respondUi: "respond_ui",
  setModel: "set_model",
  setThinking: "set_thinking",
  getSessionRuntime: "get_session_runtime",
  getGitInfo: "get_git_info",
  getGlobalApproval: "get_global_approval",
  setGlobalApproval: "set_global_approval",
  setSessionApproval: "set_session_approval",
  setOmpPath: "set_omp_path",
  // events
  sessionEvent: (id: string) => `omp-event://${id}`,
  sessionStatus: (id: string) => `omp-status://${id}`,
  sessionRuntime: (id: string) => `omp-state://${id}`,
  health: "omp-status://health",
} as const;
